#pragma once
class MyRotator;
class Transform;
class RenderSystem;
class Mesh;
class GlobalCamera;
class GameObject;
class Component;
class DrawCallBatch;
class DrawCallManager;
class AssetManager;
class Shader;
class PengTranspiler;
class Engine;
class PedryMath;
class ShaderManager;
class Renderer;
class Game;